import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { z } from 'zod'
import { sendBookingConfirmationEmail } from '@/lib/email'

const bookingSchema = z.object({
  customer_name: z.string().min(2),
  customer_email: z.string().email(),
  customer_phone: z.string().optional(),
  room_type_id: z.string().uuid(),
  package_id: z.string().uuid(),
  check_in_date: z.string(),
  check_out_date: z.string(),
  num_guests: z.number().int().min(1).max(10),
  certification_level: z.string().optional(),
  logged_dives: z.number().int().optional(),
  nitrox_required: z.boolean().default(false),
  equipment_rental: z.boolean().default(false),
  add_ons: z.array(z.object({
    id: z.string(),
    name: z.string(),
    price: z.number(),
    notes: z.string().optional(),
  })).default([]),
  special_requests: z.string().optional(),
  total_amount: z.number().optional(),
})

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const data = bookingSchema.parse(body)

    const supabase = await createClient()

    const { data: booking, error } = await supabase
      .from('bookings')
      .insert({
        ...data,
        booking_ref: '', // Will be auto-generated by trigger
        status: 'pending_payment',
        payment_method: 'bank_transfer',
      })
      .select(`
        *,
        room_type:room_types(name),
        package:packages(name)
      `)
      .single()

    if (error) {
      console.error('Booking insert error:', error)
      return NextResponse.json({ error: error.message }, { status: 500 })
    }

    // Send confirmation email (non-blocking)
    sendBookingConfirmationEmail(booking as Parameters<typeof sendBookingConfirmationEmail>[0]).catch(console.error)

    return NextResponse.json({ booking }, { status: 201 })
  } catch (err) {
    if (err instanceof z.ZodError) {
      return NextResponse.json({ error: 'Validation failed', details: err.errors }, { status: 400 })
    }
    console.error('Unexpected error:', err)
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })
  }
}
